### ISSUE TITLE
Can't understand how to proof Cantor's theorem

### ISSUE THREAD

**Issue by Spdwal** [muzimuzhi/math-notes#10]
In P198, the proof of Cantor's theorem. Tao consider a set $A := \{x \in X : x \notin f(x) \}$ and then said "this set is well-defined since $f(x)$ is an element of $2^X$ and is hence a subset of $X$". 
Why $f(x)$ is a subset of $X$?

**Comment by Spdwal** [comment]
Oh, i've got it. I've forgotten the definition of power set.

**Comment by muzimuzhi** [comment]
In my book, that sentence appears in page 195--196, not 198.
